backend:
  name: git-gateway
  branch: main
publish_mode: editorial_workflow
media_folder: "public/assets" 
public_folder: "/assets"
collections:
  - name: "post"
    label: "Post"
    folder: "src/posts"
    create: true
    slug: "{{slug}}"
    fields: 
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Malayalam Title", name: "fullTitle", widget: "string" }
      - { label: "Number", name: "number", widget: "number" }
      - { label: "Author", name: "author", widget: "string", required: false }
      - { label: "Tags", name: "tags", widget: "list" }
      - { label: "Featured Image", name: "image", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Video Link", name: "videoLink", widget: "string", required: false }
      - { label: "Translator", name: "translator", widget: "string" }
      - { label: "Translator info", name: "translatorInfo", widget: "string" }
